### ISSUE TITLE
retry: 指数退避重试策略实现

### ISSUE THREAD

**Issue by flycash** [ecodeclub/ekit#168]
**仅限中文**

## 设计与实现
在 #167 我们提供了接口设计与等时间间隔实现，那么这里要求提供一个指数退避的实现。

对于指数退避来说，用户可以设置：
- 初始重试间隔，也就是第一次重试要等多久，而后就开始按照2的指数进行增长；
- 最大重试间隔。指数增长是很快的，所以我们要防止这种增长导致重试间隔过长。比如说最长时间间隔是 10分钟；
- 重试次数，0 或者负数代表无限制；

前置任务 #167

**Comment by richzw** [comment]
尝试实现这个任务，PR已提，求review
