### ISSUE TITLE
randx: 随机验证码生成器

### ISSUE THREAD

**Issue by cancan927** [ecodeclub/ekit#206]
**仅限中文**

### 使用场景
昨天的课里用的randn方法生成随机数，这个默认随机数种子是固定的，每次生成的随机数序列是固定的，所以我想提供一个随机数生成的工具

### 行业分析
很多场景都需要一个随机码，需要支持多种验证码类型，支持数字，字母以及混合类型的随机码生成
标准库提供的Intn方法有一个默认的随机数种子，这种随机数生成的随机数序列是固定的，也就是说，程序重启，随机数会重复，
当然可以以unix时间戳来当成种子生成，但是这种方式不能生成带字母的随机序列，
但是我也没发现有哪个其它的库实现了这个功能
所以，我想这个随机码还是使用场景比较广泛的

### 可行方案
> 核心想法就是利用标准库的rand.Int63()这个方法，这个方法可以一次生成63位的int整数，而我们通常只需要4-8位就够用了，这样就可以分段多次利用这个随机数，来生成我们自己的随机码，核心代码如下：

~~~go
// generate 根据传入的随机源和长度生成随机字符串,一次随机，多次使用
func generate(source string, length, idxBits int) string {

	//掩码
	//例如： 使用低6位：0000 0000 --> 0011 1111
	idxMask := 1<<idxBits - 1

	// 63位最多可以使用多少次
	idxMax := 63 / idxBits

	result := make([]byte, length)

	//cache 随机位缓存
	//remain 当前还可以使用几次
	for i, cache, remain := 0, rand.Int63(), idxMax; i < length; {
		//如果使用次数剩余0，重新获取随机
		if remain == 0 {
			cache, remain = rand.Int63(), idxMax
		}

		//利用掩码获取有效的随机数位
		if randIndex := int(cache & int64(idxMask)); randIndex < len(source) {
			result[i] = source[randIndex]
			i++
		}

		//使用下一组随机位
		cache >>= idxBits

		//扣减remain
		remain--

	}
	return string(result)

}

~~~

### 其它
> 任何你觉得有利于解决问题的补充说明

### 你使用的是 ekit 哪个版本?
最新版本

### 你设置的的 Go 环境?
> 上传 `go env` 的结果
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\felic\AppData\Local\go-build
set GOENV=C:\Users\felic\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\developer\GoPath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\developer\GoPath;C:\Users\felic\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\developer\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\developer\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.6
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=D:\opensource\ekit\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\felic\AppData\Local\Temp\go-build3885401515=/tmp/go-build -gno-record-gcc-switches

**Comment by flycash** [comment]
感觉看起来没啥问题。你可以举一些具体的场景吗？比如说什么情况下，用自带的随机会有破绽，但是用这个会更好。又或者在性能上有竞争力吗？

**Comment by flycash** [comment]
感觉看起来没啥问题。你可以举一些具体的场景吗？比如说什么情况下，用自带的随机会有破绽，但是用这个会更好。又或者在性能上有竞争力吗？

**Comment by cancan927** [comment]
标准库的随机数算法，如果指定unix时间戳当作种子的话，只是生成随机数，其实没什么破绽；
但是局限就是，它生成的是一个”number“，而不是一个”code“；

它无法生成如”0S3eT8"这种类型的“code”，我这个方法可以生成任意类型的”code“，极端一点甚至可以生成形如”7Д4ЙSФЭ0“这种”code“。

性能上，这个方法，时间复杂度是O(n)，性能也是很好的，考虑到多数情况下”code“只需要4-8位，这个性能开销就更小了。

**Comment by flycash** [comment]
所以是随机 code？那我觉得这个很不错啊！那么是不是说在类似于验证码的场景下，我可以用它来生成随机的包含字母的验证码？

我觉得你可以发一个合并请求，我看看接口设计。整体我觉得这是一个很实用的功能，因为早期我就用过需要随机 code 的方法，但是当时我用的是 short uuid 的策略。

**Comment by flycash** [comment]
所以是随机 code？那我觉得这个很不错啊！那么是不是说在类似于验证码的场景下，我可以用它来生成随机的包含字母的验证码？

我觉得你可以发一个合并请求，我看看接口设计。整体我觉得这是一个很实用的功能，因为早期我就用过需要随机 code 的方法，但是当时我用的是 short uuid 的策略。
