### ISSUE TITLE
slice.ContainsFunc破坏性修改确认

### ISSUE THREAD

**Issue by longyue0521** [ecodeclub/ekit#228]
**仅限中文**

在提之前请先查找[已有 issues](https://github.com/ecodeclub/eorm/issues)，避免重复上报。

并且确保自己已经：
- [x] 阅读过文档
- [x] 阅读过注释
- [x] 阅读过例子

### 你的问题

`slice.ContainsFunc`方法在[v0.0.7](https://github.com/ecodeclub/ekit/blob/v0.0.7/slice/contains.go#L26)的方法签名如下:

```go
// ContainsFunc 判断 src 里面是否存在 dst
// 你应该优先使用 Contains
func ContainsFunc[T any](src []T, dst T, equal equalFunc[T]) bool {
```
在[v0.0.8](https://github.com/ecodeclub/ekit/blob/v0.0.8/slice/contains.go#L26)的方法签名如下:

```go
// ContainsFunc 判断 src 里面是否存在 dst
// 你应该优先使用 Contains
func ContainsFunc[T any](src []T, equal func(src T) bool) bool {
```
请确认是否预期内的修改,如果是请将v0.0.8及以后版本中`ContainsFunc`的注释内容同步修改.

### 你使用的是 ekit 哪个版本?
v0.0.7 v.0.0.8
### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by flycash** [comment]
是的。因为早期的接口设计不合理。

**Comment by longyue0521** [comment]
> 按照道理应该发一个大版本的，但是目前我认为 ekit 中还有很多接口还需要观察，所以 0.0.x 将处于一段时间的验证状态，等我正式发布 0.1.0 可以看做是第一个稳定的版本。

好的
