### ISSUE TITLE
slice 转 map

### ISSUE THREAD

**Issue by flycash** [ecodeclub/ekit#248]
**仅限中文**

### 使用场景

在实践中，经常遇到需要将一个 slice 转化为一个 map 的场景。这种转化分成两大类：
- value 的类型就是 slice 中的元素类型
- value 的类型是新类型

但是对于 key 来说，大部分场景下都不太会是 slice 的元素类型。

### 可行方案
> 如果你有设计思路或者解决方案，请在这里提供。你可以提供多个方案，并且给出自己的选择

我需要两个接口：
```go
// 如果 eles 是 nil，那么返回一个空的 map 而不是返回 nil
func ToMap[Ele any, Key any] (eles []Ele, keyFunc func(ele Ele) Key) map[Key]Ele
// 命名无能，你可以搞一个更加牛逼的名字。
func ToMapV[Ele any, Key any, Val any] (eles []Ele, keyFunc func(ele Ele) (Key, Val)) map[Key]Val
```
从实现的角度来说，ToMap 应该直接调用 ToMapV 来实现

### 其它
> 任何你觉得有利于解决问题的补充说明

### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by dxyinme** [comment]
这里的Key是否该为comparable

改了一下函数泛型顺序，可以改成这样
```go
// 如果 eles 是 nil，那么返回一个空的 map 而不是返回 nil
func ToMap[Key comparable, Ele any] (eles []Ele, keyFunc func(ele Ele) Key) map[Key]Ele
// 命名无能，你可以搞一个更加牛逼的名字。
func ToMapV[Key comparable, Ele any, Val any] (eles []Ele, keyFunc func(ele Ele) (Key, Val)) map[Key]Val
```

**Comment by flycash** [comment]
没有 ToMap 这个方法吧？在mapx 下有一个。这里我是准备放过去 slice 包里面的。

另外顺序的话，因为考虑到有 Val 和没有 Val 两个版本，并且我希望 Key 和 Val 挨着，所以只能是 Ele 在最前，或者 Ele 在最后。

**Comment by dxyinme** [comment]
> 没有 ToMap 这个方法吧？在mapx 下有一个。这里我是准备放过去 slice 包里面的。
> 
> 另外顺序的话，因为考虑到有 Val 和没有 Val 两个版本，并且我希望 Key 和 Val 挨着，所以只能是 Ele 在最前，或者 Ele 在最后。

那我理解了，开搞
