### ISSUE TITLE
提供 Must 和 MustT 函数，简化错误处理

### ISSUE THREAD

**Issue by dxyinme** [ecodeclub/ekit#250]
**仅限中文**

### 使用场景

提供 MustT(val T, err error) T 函数， 让出现error的地方直接panic，简化一些逻辑的处理
比如在程序启动的时候存在一些初始化函数，如果这些函数出错就直接panic。
```go
原先可能需要
a, err := Init()
if err != nil {
      panic(err)
}

现在只需要
a := MustT(Init())
```

### 行业分析
> 如果你知道有框架提供了类似功能，可以在这里描述，并且给出文档或者例子

### 可行方案

两个函数
```go
func MustT[T any] (val T, err error) T
func Must(err error)
```

### 其它
> 任何你觉得有利于解决问题的补充说明

### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by flycash** [comment]
单独提供这个方法其实没什么必要，因为我觉得 if err != nil 这种判定方式更加直观。另外一个就是，如果要引入类似的判定，那么还不如引入一个完整的 require 包，类似于测试用的 require 包。

**Comment by flycash** [comment]
> a := MustT(Init())
这种写法在 Init 返回两个返回值的情况下，应该是编译错误，

**Comment by dxyinme** [comment]
> > a := MustT(Init())
> > 这种写法在 Init 返回两个返回值的情况下，应该是编译错误，

应该不会编译错误，不指定类型他会自己推断的

**Comment by dxyinme** [comment]
有道理，引入require包会更直接，那我直接用那个
