### ISSUE TITLE
pool: TaskPool 的可观测性设计

### ISSUE THREAD

**Issue by flycash** [ecodeclub/ekit#98]
**仅限中文**

### 使用场景

正如 #50 中 @lincolnzhou 中提到的，一个符合生产条件要求的 TaskPool，必须要能够暴露观测接口，允许用户监控池子本身的状态。

但是我们可以对 #50 中讨论的观测性进一步讨论：

- 运行指标（百分比+数量+top）
  -   任务运行时长
  -   任务等待时长
  -   任务池活跃度
  -   队列容量
- 运行时报警策略
  - 任务运行超时
  - 任务池活跃度
  - 阻塞队列容量
  - 触发拒绝策略
  - 主流软件告警（微信，钉钉，飞书）
- 监控运行可视化
  - Prometheus + Grafana第三方采集监控
  - 内置数据池数据采集 + 监控

核心是三个点：运行指标、告警策略与可视化。

这里我们站在 ekit 作为一个工具的角度出发，那么告警策略和可视化两个点 ekit 比较无能为力。因为 ekit 本身并不会与重量级的 Grafana 或者微信钉钉之类的集成。这种事情我们可以额外提供工具，或者在文档里面建议用户进行监控。

对于 ekit 本身来说，它只需要暴露”必要的“内部状态就可以了。用户可以监控这些内部状态，然后自己集成这些告警策略和可视化平台。

因此一切的问题都在于，该暴露什么状态，以及如何暴露。

目前来说，前面 lincolnzhou 提到的指标，以及我能够想到的一些状态：
- 任务运行时长：理论上用户可以自己在任务里面监控，但是我们也可以暴露这种数据，因为本身它算是一个 AOP 的需求，毕竟所有的任务都需要监控运行时长
- 等待时长：类似前者。与之类似的指标有阻塞队列容量，阻塞队列中等待的任务数（或者剩余容量），提交的时候被拒绝的任务数量
- 活跃度：这个可以用运行中协程数量来进行替代
- 任务运行状态：成功、失败或者超时。鉴于当前我们的 TaskPool 设计了 context 接口，所以超时控制我们也可以做到的；

### 行业分析
> 如果你知道有框架提供了类似功能，可以在这里描述，并且给出文档或者例子

### 可行方案
> 如果你有设计思路或者解决方案，请在这里提供。你可以提供多个方案，并且给出自己的选择

从设计上来说，大体有：

#### 回调机制
我们允许用户注册一些回调，比如说 OnPanic 和 OnError，它们会在任务触发了 Panic 或者返回了 error 的时候执行。例如
```go
type Pool struct {
    OnPanic func(t, panicVal any) 
}
```
#### 观察者模式
我们设计一些 Observer 接口，用户在使用 TaskPool 的时候可以传入不同的 Observer：
```go
type TaskObserver struct {
    // 观测具体的任务的状态
   // int 来表达 task 的执行情况可能不是很合适，还要进一步考虑
   Observe(status int, task Task, duration time.Duration)
}

type PoolObserver struct {
    // 观测池子本身的状态，例如阻塞队列的情况
    Observe(...)
}
```
我们可以针对任何一个观测的东西都设计出来接口，也可以考虑将 TaskObsever 和 PoolObserver 进一步细分。

我一般的设计倾向都是细分接口，然后通过组合来组成大的接口。

#### channel 暴露状态
这种形态，我们就是单纯暴露一个 channel，而后往 channel 里面写数据。这里我们可以引入一个额外的 Event 抽象：
```go
func (p Pool) Stats() <- chan Event {
    // ... 
    return ch
}

// 对于用户来说
func MyMetrics() {
     ch := p.Stats()
     event := <- ch
     switch event.(type){
     case TaskEvent:
               // 记录 Task 发生的事情  
     }
}
```

Event 可以设计成接口，然后用户进行 switch type 判断具体发生了什么事。但是使用 channel 不太好的地方就是不好估计 channel 的容量，并且可能阻塞住我们 TaskPool 本身

#### 装饰器模式

装饰器只能解决 Task 的观测和 Pool 本身的部分观测问题。

类似于我们解决 panic 的思路。我们可以通过封装一个新的 Task:
```go
type metricTask struct {
   t Task
   observer Oberver
}

func (t metricTask) Do(ctx context.Context) error {
    startTime := time.Now()
    t.t.Do(ctx)
    endTime := time.Now()
    t.obsever.Observe(endTime-startTime)
}
```

这种设计形态要和前面的 Observer 或者回调结合在一起。优点就是我们将观测这种事情改成了一种非侵入式的方案。

### 其它
> 任何你觉得有利于解决问题的补充说明

Task 的名字问题。类似于在观测的时候，用户可能需要给 Task 一个名字，例如 "task-find-hot-product"。

但是从目前的接口设计来看，我们并没有直接支持。

好在 Task 是一个接口，也就是用户可以完全实现自己的 Task（也可以是我们提供一个）：
```go
func MyTask() {
    Name string
}
```
不过目前我们是对 Task 进行来包装，来解决 panic 的问题，所以实际上我们在考虑通知用户发生了什么事情的时候，要把原始的 Task 传回去。

另外一种思路是我们暴露一个新的接口：
```go
type NamingTask interface {
    Name() string
    Task
}
// 或者

type Naming interface {
    Name() string
}
```
这种形态也是可以的，我们只需要在实现内部检测是不是 NamingTask。

### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by Stone-afk** [comment]
这里我偏向于用装饰器模式，但这是否意味这只要提供可观测性的接口的实现 以及对原有的任务池增加 对应的监控指标的方法就行？比如在 OnDemandBlockTaskPool 实现计算等待时长的方法

**Comment by Stone-afk** [comment]
‘’‘’
type TaskObserver interface {
	Observe(ctx context.Context, task pool.Task, status uint64)
}

type PoolObserver interface {
	Observe(ctx context.Context, pool pool.TaskPool, status uint64)
}


‘’‘’
